# Generated by Django 2.0.6 on 2018-08-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='face_img',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
